### ISSUE TITLE
Interactive terminal

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#10]
We want the ability to create sections which behave and look like a terminal window. You can see an example (an example, or that we would like them to customise this code and embed it in our backend?) of this here: https://term.m4tt72.com/

This should be a reusable block that we can create commands for in the backend. We will reproduce this for 3 sections with different sets of content and commands.

The idea of these sections is they provide interactivity for us to surface content by the user “investigating”. In the majority of queries, the commands will bring up text, but we would like the ability for the terminal to query a hyperlink/external source, as it currently does in the above link. 

https://github.com/jcubic/jquery.terminal
https://terminal.jcubic.pl/api_reference.php
https://www.jqueryscript.net/other/terminal-emulator-command.html
https://www.jqueryscript.net/blog/best-terminal-emulator.html

Try these 2:
https://github.com/mkrl/ttty (can add as node dep)
https://github.com/m4tt72/terminal is the demo at https://term.m4tt72.com - we could deploy a few of these and embed in iframe. Not immediately clear if we can embed as svelte component)
https://github.com/HusnainTaj/KonsoleJS (not stable)

**Comment by stuartleech** [comment]
Christo has mapped them out - 30 pages of commands and responses!

From page 17 onwards: https://docs.google.com/document/d/1bKa5S4n9IQbs4gT06_LV-WwOqkGuAF0l/edit?usp=sharing&ouid=107021246338194950310&rtpof=true&sd=true
