### ISSUE TITLE
Data loss portraits

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#11]
## Plan

- 866 images in `/public/images/portraits` numbered from `0.jpg` to `865.jpg`
- render at 0 opacity and fade in at random over time
  - render all in a grid
  - fade all in at same timing
  - fade in individually

This section of the site is a visual representation of data loss. We have 2000+ portraits that can populate this section, but we'll try with randomised display of 200 of them that come into focus randomly.

Initially this section should start as a set of white boxes as used previously, these should gradually fade in with the pixelated portraits. 

The tickers from #13 will overlay this

![image](https://github.com/cookiewolf/bi4c8d/assets/861172/443e1d44-cd2b-4074-913b-30c0b6480de3)

**Comment by stuartleech** [comment]
https://drive.google.com/drive/folders/1FlmYlLSpLAA1mu-MWAOTOTCyztgnbPSk?usp=sharing

**Comment by katjam** [comment]
rename files in bash:
`I=0`
` for f in *.jpg; do mv -n "$f" "${I}.jpg" ; let I=${I}+1; done`
