### ISSUE TITLE
Add context (table of content or side box that changes as scroll down)

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#154]
- [x] Add context to CMS
- [x] Display context
- [x] Style context box & sections
- [x] Add all content stubs (because can't add new ones in CMS)
- [x] Display section progress e.g. 1 of 22
- [x] Conditional display & placement of context box
- [x] Verify with Stuart that the right fields are optional
- [x] Remove title from display

**Comment by stuartleech** [comment]
Adding notes here for this issue. 

Have "fixed header" that has the intro content and then the body content scrolls over the top of it.

The footer on this page in reverse or am I mad? https://www.cera-groupecera.com/en/

**Comment by stuartleech** [comment]
Table of Contents:

http://gregfranko.com/jquery.tocify.js

https://tscanlin.github.io/tocbot/

**Comment by katjam** [comment]
Timeline:
https://medium.com/@kyleducharme/contextual-scrolling-ac27459bc68e

**Comment by stuartleech** [comment]
https://www.bbc.co.uk/news/resources/idt-sh/the_reykjavik_confessions contextual scrolling with chapters

**Comment by stuartleech** [comment]
[Context Menu - Collapsed.pdf](https://github.com/cookiewolf/bi4c8d/files/15416581/Context.Menu.-.Collapsed.pdf)
[Context Menu - Expanded.pdf](https://github.com/cookiewolf/bi4c8d/files/15416582/Context.Menu.-.Expanded.pdf)

**Comment by stuartleech** [comment]
<img width="274" alt="Screenshot 2024-06-03 at 13 04 24" src="https://github.com/cookiewolf/bi4c8d/assets/15141003/afff0b54-9cd6-4694-922b-626ebe9c628a">
<img width="249" alt="Screenshot 2024-06-03 at 13 04 19" src="https://github.com/cookiewolf/bi4c8d/assets/15141003/70f30181-fa51-4fd5-b9b0-a02fac8139fb">

**Comment by katjam** [comment]
Content doc: https://docs.google.com/document/d/1bKa5S4n9IQbs4gT06_LV-WwOqkGuAF0l/edit

**Comment by stuartleech** [comment]
The content for the table of contents is here: https://docs.google.com/document/d/1tpKuItanMULGK14biDqT6PpSTG0MvmNdkGjcTnL0J7s/edit?usp=sharing

**Comment by katjam** [comment]
@stuartleech I added context content for sections 1 to 17 but as you suspected, the numbers maybe don't correspond. Especially since the doc you linked actually goes up to section 22 but we only have 17. :grimacing: 

I'll keep getting the function and design working and we can sort the content once in place.

**Comment by aaaaargZombies** [comment]
> @aaaaargZombies do you want to take over and do some styling on this?

sounds good to me

**Comment by katjam** [comment]
Styling to be completed as part of #236
