### ISSUE TITLE
Populate Lockbit Content

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#166]

**Comment by stuartleech** [comment]
[Lockbit-RoyalMail-Conversation.txt](https://github.com/cookiewolf/bi4c8d/files/14898962/Lockbit-RoyalMail-Conversation.txt)

I've got the conversation in plain text format - I think we'll need to edit it down but before I ask Christo is there a quick way of populating it from the text file - don't worry if not I can do some copy and pasting!

**Comment by katjam** [comment]
I think the easiest thing would be copy pasting directly in the markdown files, not through the CMS.

As in start with: lockbit-one.md

```
---
section: section-ten
title: mesage one
datetime: 2021-12-15T21:21:29.472Z
side: left
---
If people are not awake to the fact this is all about imposing digital identification and apartheid by now then there’s no helping them at all.

This isn’t about health, it’s about CONTROL!!!

It always has been.
```
Replace the content in your text editor and then save as lockbit-two.md etc.

Files stored in `content/messages` will be ingested by the CMS.

**Comment by stuartleech** [comment]
I've been doing it through the CMS as the timestamp thing is impossible but it's actually pretty quick so its all good. 

However they seem to have lost the correct order? They are all the same date and then chronological by time but it seems to have put them out of sync?

**Comment by katjam** [comment]
I maybe am only ordering by date - not time. Will check.
