### ISSUE TITLE
[Bug]: Stop terminal scroll

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#171]
https://github.com/mkrl/ttty/blob/7570c9a0442200e0603a23f147bae1c64345a7f4/src/api/print.ts#L12

**Comment by katjam** [comment]
Had another look at this. Not much progress but I think we might need to add a parameter to the scrollintoview function of `{ inline: "nearest"}`

I tried overriding it in the source and using my own function but no joy - there was caching in the way maybe on the source one and mismatched resolutions in my local.

I also tries a variety of container display and position settings. Have reached out to Nick and will reach further if he doesn't have any ideas.

**Comment by stuartleech** [comment]
Thanks for trying further! What a pain - when I load https://bi4c8d.netlify.app/ it scrolls me to the terminal automatically, which is different to what yours was doing?

**Comment by stuartleech** [comment]
Yeah so on page load it scrolls me down to it I hadn't really noticed before!

**Comment by katjam** [comment]
Great. :)

**Comment by katjam** [comment]
Maybe the easiest is to fork it.... or actually, it's pretty simple to maybe write in Elm. I'll sleep on it.

**Comment by katjam** [comment]
I've slept on it for 3 minutes and I think it'd take me 1 hour to implement in Elm. No idea what that didn't occur to me before. Even if you double that and double again - it's 1/2 day. I'll fix the other bugs first.

**Comment by stuartleech** [comment]
Ha, power nap! 

That sounds great to me

**Comment by katjam** [comment]
Closed a won't fix. Will implement in Elm.
