### ISSUE TITLE
Styling tweaks

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#186]
## Description
What needs doing?

## Plan
- [x] terminal section (BG) full view height
- [x] margin before terminal (after main text)
- [x] Graph full height
- [x] Graph title white (and default font)
- [x] replace svg for main text icons

**Comment by stuartleech** [comment]
![main-text-icons](https://github.com/cookiewolf/bi4c8d/assets/15141003/68adc403-5154-4bec-b2c4-2e18fb82708c)
