### ISSUE TITLE
Add comment section to context (hyvor?)

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#21]

**Comment by katjam** [comment]
![image](https://github.com/user-attachments/assets/19434f78-ca03-49cc-80b5-443050333307)

**Comment by stuartleech** [comment]
<script async src="https://talk.hyvor.com/embed/embed.js" type="module"></script>
<hyvor-talk-comments website-id="YOUR_WEBSITE_ID" page-id=""></hyvor-talk-comments>

**Comment by stuartleech** [comment]
https://talk.hyvor.com/docs/install

**Comment by stuartleech** [comment]
```
<script async src="https://talk.hyvor.com/embed/embed.js" type="module"></script>
<hyvor-talk-comments
	website-id="11670"
	page-id=""
></hyvor-talk-comments>
```

Detailed info here: https://talk.hyvor.com/console/11670/install

I think we might need to just hide the comments section with CSS but I've asked their support

There's quite a few options that can be configured: https://talk.hyvor.com/docs/comments#component

**Comment by stuartleech** [comment]
I've customised this from the UI so It should just be a case of embedding it with a unique page ID for each section I think...

**Comment by katjam** [comment]
Do you want to share your login for the account with me?

**Comment by katjam** [comment]
Re-opening to test & verify styles once url has been whitelisted

**Comment by stuartleech** [comment]
Oh I can do this now!

I thought that was the domain I used but obviously didn’t!


--
Stuart Leech
07834 901 032

**Comment by stuartleech** [comment]
<img width="701" alt="Screenshot 2024-08-10 at 16 24 14" src="https://github.com/user-attachments/assets/825d7b91-8fc1-43c5-bde4-ff561f281242">

I've set it to use the dark pallete which should have a black background a white text but that doesn't seem to be working

I need to change the icons to white ones but I can definitely do that and I've limited it to 5 

<img width="437" alt="Screenshot 2024-08-10 at 16 25 39" src="https://github.com/user-attachments/assets/581726e9-9da8-42ab-8b04-fe942e79a307">

**Comment by katjam** [comment]
It's rendering but not sending/fetching the updates. I might need to wire something up.

**Comment by stuartleech** [comment]
I asked their support you have to reload the comments section each time, there's an api call documented here but not sure how that gets implemented?

https://talk.hyvor.com/docs/comments#api

**Comment by stuartleech** [comment]
> You have to do something like this:
> 
> ```
> const comments = document.querySelector("hyvor-talk-comments");
> comments.reload();
> ```
> 
> Listen to the changes of page-id
> On each listen, call the reload() method as above (assuming you only have one hyvor-talk-comments element on your website)

**Comment by katjam** [comment]
Track / reload didn't work. Re-opening.
