### ISSUE TITLE
New content and 22 sections

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#210]
renumber according to google doc with context

- [ ] Intro text (Main text top section 1) styled differently by Stuart (no change to section)
- [ ] #215
- [ ] #216
- [ ] Draggable gallery (5.5 before HMRC terminal) (new section 8)
- [ ] #214

1 <- 1
2 <- new
3 <- new
4 <- 2
5 <- 3
6 <- 4
7 <- 5
8 <- new
9 <- 6
10 <- 7
11 <- 8
12 <- 9.1
13 <- new
14 <- 9.2
15 <- 10
16 <- 11
17 <- 12

**Comment by stuartleech** [comment]
Draggable messages and gallery example

![Moveable Elements Image Gallery](https://github.com/cookiewolf/bi4c8d/assets/15141003/8ea83188-0fdf-4dfb-b066-161ec0e7beab)
![Social Messaging Example](https://github.com/cookiewolf/bi4c8d/assets/15141003/fe01ac18-2a06-4176-8466-2c7d4d0d7da6)

**Comment by katjam** [comment]
I'm considered naming the sections rather than numbering - because precisely this reason, It's easier to re-order, but also seems like this system is in place now and marginally less work to just keep it going like this.

**Comment by katjam** [comment]
![IMG_20240706_124121.jpg](https://github.com/cookiewolf/bi4c8d/assets/861172/6641235f-caee-40de-a85d-39f25b31364a)

**Comment by katjam** [comment]
![image](https://github.com/cookiewolf/bi4c8d/assets/861172/6acfcc53-711d-4a54-a520-22c379dfb30b)

**Comment by katjam** [comment]
![IMG_20240706_125241.jpg](https://github.com/cookiewolf/bi4c8d/assets/861172/b3731d09-8050-4733-9b08-5bc27ec18918)

**Comment by katjam** [comment]
Closed by #213
