### ISSUE TITLE
Design Changes

### ISSUE THREAD

**Issue by stuartleech** [cookiewolf/bi4c8d#223]
## Sub tasks

- [x] #227
- [x] #229
- [x] #231
- [x] #233

![Bifurcated Design Finesse](https://github.com/user-attachments/assets/b7f7e534-46c6-4105-b453-7dec64152573)

https://www.figma.com/design/WsHHoFWCBoxKvexKojQhfc/Bifurcated?node-id=605-289&t=czXWm0vrHvudDKFG-1

**Comment by aaaaargZombies** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice

**Comment by stuartleech** [comment]
- [ ] Make background black apart from intro section
- [ ] Intro text should be black text on a white background without a box around the content
- [ ] Title font should be TT Firs Neue
- [ ] Body font should be Courier Prime (Google Font)
- [ ] Main text outline boxes should be handrawn lines as per design

**Comment by stuartleech** [comment]
SVG Lines
![Underline_10](https://github.com/user-attachments/assets/d00a7ffa-9332-43f7-939e-3e3f4fbfe2eb)
![Underline_08](https://github.com/user-attachments/assets/03464920-a4f1-4178-b545-e9bb7bac418f)
![Underline_05](https://github.com/user-attachments/assets/abfafadb-91bc-4d9f-b2db-bc5a905f0fa7)
![Underline_02](https://github.com/user-attachments/assets/390b90d7-d3d7-48f6-8500-c236cb0df211)
![Underline_01](https://github.com/user-attachments/assets/7dc7865b-0eff-40c2-abfd-b32ba7ba7f12)

**Comment by stuartleech** [comment]
Font Files 
[TT Firs Neue Var Roman.woff.zip](https://github.com/user-attachments/files/16360848/TT.Firs.Neue.Var.Roman.woff.zip)
[CourierPrime-Italic,CourierPrime-BoldItalic,CourierPrime-Bold.zip](https://github.com/user-attachments/files/16360849/CourierPrime-Italic.CourierPrime-BoldItalic.CourierPrime-Bold.zip)

**Comment by aaaaargZombies** [comment]
@stuartleech are these posts intended to be moved over to the new design or is that just for draggable posts?

![image](https://github.com/user-attachments/assets/93427cc1-8a10-46b0-8dc1-011292768407)

If so I'll make a new ticket but leaving them as is for now

**Comment by aaaaargZombies** [comment]
all tasks done
