### ISSUE TITLE
Finesse Faces Fading in 

### ISSUE THREAD

**Issue by stuartleech** [cookiewolf/bi4c8d#224]
There's a bunch of things that would make this optimal, and some things that are essential. This ticket will be used to track progress of sub tasks.

### critical

-  [x] #248

### important

- [ ] text should be varied / individualized
- [x] #251
  1. first image
  2. corresponding text
  3. second image
  4. corresponding text
  5. third image
  6. corresponding text
- [ ] placement of blurred faces should be mapped to the locations of the white boxes/censored faces on the images above.
- [ ] sizes of the blurred faces should be mapped to the locations of the white boxes/censored faces on the images above.

  
 ### desirable  
  
- [ ] animation happens on top of the last photo not below
- [ ] animation responds to scroll
- [ ] user can scroll off animation once complete

**Comment by katjam** [comment]
Closing as won't fix on enhancements
