### ISSUE TITLE
style context box

### ISSUE THREAD

**Issue by aaaaargZombies** [cookiewolf/bi4c8d#236]
## User story

expanding on the work Katja has done on #154

## Acceptance criteria
- [ ] context menu appears in a fixed position on the page
- [ ] details are collapsed by default

## Implementation notes & questions

will probably need to announce to screen readers when new information becomes available

It was decided that the title would be removed so just a reference to the section number on the right.

![image](https://github.com/user-attachments/assets/98b9690c-28f5-430d-859c-dcf7d468779e)

![image](https://github.com/user-attachments/assets/d657cbca-c61b-4aa5-9a70-9439cea83964)

**Comment by katjam** [comment]
Ah perfect - you made a new issue. I'll close #154
