### ISSUE TITLE
Final Tasks

### ISSUE THREAD

**Issue by stuartleech** [cookiewolf/bi4c8d#261]
- [ ] Change font size of "final-ticker" to 2rem

Reordering of elements

There's some slight re-ordering required in terms of sections in the wrong place and then where there is context available, this is definitive. But for instance at the moment the intro text and social media posts are "Section 1" but they both have their contexts so should be split up....

Section Number | Content | Type | Context
-- | -- | -- | --
1 | Introduction | Main Text | Has Context
2 | Social Media Posts | Posts | Has Context
3 | Public Trust | Graph | Has Context
4 | Telegram channels | Graph | Has Context
  | Ulterior Motives (UM) intro | Main Text | No Context
5 | UM social - | Posts | Has Context
  | UM newspapers | Draggable Images | No Context
6 | Panic Lit project | Draggable Images | Has Context
  | Illegal, unnecessary and disproportionate essay | Main Text | No Context
7 | Public Order + Safety spending | Graph | Has Context
8 | Illegal, unnecessary and disproportionate essay part 2 | Main Text | Has Context
9 | Facial recognition project | Custom | Has Context
10 | Incompetence intro | Main Text | Has Context
11 | Incompetence social - Posts | Posts | Has Context
  | Incompetence newspapers | Draggable Images | No Context
12 | HMRC Terminal | Terminal | Has Context
13 | Facebook Data Loss portraits | Custom | Has Context
  | Ransomwatch terminal | Terminal | No Context
14 | Human cost of a data breach essay | Main Text | Has Context
15 | Royal Mail negotiation messenger | Messages | Has Context
  | Ana messenger | Messages | No Context
16 | Hackney social | Posts | Has Context
17 | Outro | Main Text | Has Context

**Comment by katjam** [comment]
lol. !Final Tasks"

**Comment by katjam** [comment]
If you are happy with the decision, I think I will use their names rather than numbers since everything has to move anyway... or is that a bad idea?

**Comment by stuartleech** [comment]
Yeah that’s fine I think it will help, sorry!


--
Stuart Leech
07834 901 032

**Comment by stuartleech** [comment]
Hello!

Sorry there's a couple of things I can't figure out which I'm hoping will be quick, sorry!

- [ ] Is there a way to make all external links open in a new window without editing each on manually?
- [ ] There's a link under "accountability sorry" in the hmrc terminal which is defaulting to blue can we make it white underlined?
- [ ] I can't work out the css class I need to get rid of the "what's your reaction" title on the hyvor widget, any thoughts?
- [ ] Can we move the "since you've been on this website" text above the tickers with the other text?
- [ ] Can we create a context menu for the ransomware terminal?
- [ ] I couldn't work out how to get rid of the link at the end of the lockbit chat, that link is in the context now so isn't need. I found the code but when I removed it it messed up the structure and indentation...

**Comment by katjam** [comment]
> external links open in a new window

I assume you mean new tab here. @stuartleech

**Comment by katjam** [comment]
> Can we move the "since you've been on this website" text above the tickers with the other text?

Do you still want so much black around it or just under the text "Between July 2020 and June 2021..." as another paragraph?

**Comment by stuartleech** [comment]
Yeah as another paragraph will work, thank you

**Comment by katjam** [comment]
I'm actually leaving with all the black, I think it looks good like that... but we can remove some of the padding if you don't like it.

**Comment by stuartleech** [comment]
Thanks for this Katja!

Only thing I've spotted is that Hyvor has decided to disappear completely?! Sorry it's such a pain!

**Comment by katjam** [comment]
Whoops! I assumed the warning on my local version was in the section I removed... I'll take another look.

**Comment by katjam** [comment]
I think it's fixed.

**Comment by katjam** [comment]
Do you still need to change the final ticker font size, or can we close this?
