### ISSUE TITLE
[Bug]: Telegram Growth Channel Graph

### ISSUE THREAD

**Issue by stuartleech** [cookiewolf/bi4c8d#271]
1. All 7 datasets aren't displaying
2. Can we display month on the x axis?

**Comment by katjam** [comment]
This may be related:

``` 
reason: 'unidentified alias "*Events"',
  mark: Mark {
    name: null,
    buffer: 'section: public-trust\n' +
      'context: **Events in the timeline**\n' +
      '\n' +
      'May 1997: Change of government\n' +
      '\n' +
      'October 2001: Beginning of the War in Afghanistan\n' +
      '\n' +
      'May 2003: Beginning of Iraq War\n' +
      '\n' +
      'May 2005: General Election\n' +
      '\n' +
      'June 2009: MPs Expenses Scandal\n' +
      '\n' +
      'May 2010: Change of government\n' +
      'fact-check: ""\n' +
      'references:\n' +
      '  - reference: https://journals.sagepub.com/doi/full/10.1111/1467-856X.12073#fig1-1467-856X-12073\n' +
      '\x00',
    position: 39,
    line: 1,
    column: 17
```

**Comment by katjam** [comment]
I've removed that markdown from the context field, but if we want that heading to be in bold, we need to fix that in the render.

**Comment by katjam** [comment]
I've fixed it again with the bold now. Context can contain markdown, but it was put in without escaping the special characters and had also then generated a bunch of extra frontmatter fields because of the `:` after each date.

**Comment by stuartleech** [comment]
Ah Christo added the context today but the contents of the graph wasn't displaying correctly before that was entered...
