### ISSUE TITLE
Show intro on own page with button to explore content

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#282]
This issue is for controls to make intro a separate page. There is another for styling. #283

**Comment by katjam** [comment]
@stuartleech Do you want people to be able to go back to the intro once they've entered the content. It will default to showing intro on load or refresh but there should maybe be a button to go back, at the top and or bottom of page.

**Comment by stuartleech** [comment]
That would be good, could we put something in the context menu, or do you think just a button at the end?

**Comment by katjam** [comment]
I'm not sure. Maybe something like - obviousl;y lined up better and in black.
![image](https://github.com/user-attachments/assets/89b2cc6f-4e2f-4685-aff5-e682eebb7641)

**Comment by katjam** [comment]
There is also some funky scroll behaviour because of where the app thinks it is when the button is pressed. You'll see.

**Comment by stuartleech** [comment]
Yeah let's do that
