### ISSUE TITLE
Intro styling

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#283]
Add some animations and interesting visuals like:
https://current.withgoogle.com/the-current/conspiracy-theories/
https://codepen.io/soulwire/pen/mEMPrK

- [x] #292
- [ ] and then Title scrambles when hover over it
- [ ] investigate background spotlight thing
- [ ] #295

**Comment by katjam** [comment]
@stuartleech So many cool effects here: https://devdevout.com/css/css-hover-effects

This one in particular looks like it might be applicable to Bifurcated: https://codepen.io/iamryanyu/pen/bvwapv

**Comment by katjam** [comment]
This one looks good for spotlight - also has click effect: https://codepen.io/GeorgePark/pen/ELemzZ

Others for ref:
https://blog.finiam.com/blog/spotlight-effect-with-js-and-css
https://www.geeksforgeeks.org/how-to-create-a-spotlight-effect-using-html-and-css/

**Comment by stuartleech** [comment]
So cool, can we try the spotlight on the intro and see how it looks? I like the example you suggested but maybe make the spotlight slightly softer edged?

The glitch effect might be cool to implement somewhere else but I'll see what Christo thinks

**Comment by katjam** [comment]
Closing as partially completed and have split tasks off.
