### ISSUE TITLE
Add section placeholders with IDs for all sections

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#35]
## Acceptance criteria
- [ ] View contains all sections from prototype with a div including `id` attribute
- [ ] All sections added as options for main-text in CMS
- [ ] Appropriate sections added to CMS lists for messages

**Comment by katjam** [comment]
@stuartleech If you were to name the sections, what would the names be? I'm trying to break down into views similar to a traditional site with pages. I decided it's not helpful to call them section 1, 2, 3 etc and would rather the divisions are meaningful for you.

**Comment by stuartleech** [comment]
@katjam How do you mean? I mean this is slightly different to labelling the content types but I'm not sure how else you could label them if they could contain different content? Or do you want me to label each section of the visual design like "intro text" "initial telegram messages" etc?

**Comment by katjam** [comment]
I guess I was just thinking conceptual sections, like your second thought there. Kind of like what is the purpose of each group of content. So that it makes sense to have some main text and a graph for example in one section.

But maybe I'm barking up the wrong tree.

**Comment by stuartleech** [comment]
Oh I see, I can go through and label them all if that helps but I think numbering isn't the worst solution

**Comment by katjam** [comment]
OK I'll stick with numbering then. I guess if you label them then at least the design ref will tie in with the code.

**Comment by katjam** [comment]
Closing as a won't fix. Will add as I go rather than make placeholders - the system might change.

**Comment by katjam** [comment]
Actually I think this is useful after all.
